// @ts-check
//
// test/gsd-verify-cli-handler.test.js — Tests para el thin CLI handler
// `runGsdVerifyCli` de `src/cli/gsd-verify.js`.
//
// Cobertura:
//   - Exit codes 0/1/2 (Pitfall #6, Opción A): verdict pass/fail/missing/malformed → 0;
//     session not found / is not GSD → 1; provider fetch failure transient → 2.
//   - JSON output (--json) parseable; human output NO parseable como JSON.
//   - renderHuman switch exhaustivo sobre los 4 verdicts.
//   - DI: runVerifyFn mockeable, no toca filesystem real.
//   - Wiring estático en src/cli.js (CLI1..CLI4) — lectura de archivo vs spawnSync.
//
// El handler es thin: toda la lógica vive en src/gsd/verify.js (Plan 10-02).
// Aquí verificamos SOLO la capa argv → delegación → render → exit code.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { runGsdVerifyCli } from '../src/cli/gsd-verify.js';

/**
 * Captures writes to stdout/stderr for assertion.
 */
function makeStdoutStub() {
  let buf = '';
  return {
    write: (s) => {
      buf += s;
    },
    get: () => buf,
  };
}

// Plan 15-04 Task 1: result.plane.comment_body now exposes the markdown
// generated by renderComment. Builders include realistic comment_body strings
// so that Task 2 summary-slice tests have deterministic input.

/** Shorthand builder for a pass-verdict result from runGsdVerify. */
function passResult() {
  return {
    verdict: { action: 'pass', phase_id: '10', must_haves: 8 },
    plane: {
      commented: true,
      transitioned: true,
      comment_body: [
        '[kodo:gsd] ✅ Phase 10 verificada — Orchestrator gate',
        '',
        '- Must-haves: 8/8 verificados',
        '- Gaps: 0',
        '- Transicionada a Review',
      ].join('\n'),
    },
    session: { session_id: 's1', task_ref: 'KL-42', phase_id: '10' },
  };
}

function failResult() {
  return {
    verdict: {
      action: 'fail',
      phase_id: '10',
      reason: 'gaps-found',
      detail: 'gaps_count=2',
    },
    plane: {
      commented: true,
      transitioned: false,
      comment_body: [
        '[kodo:gsd] ❌ Phase 10 bloqueada — Orchestrator gate',
        '',
        'Motivo: gaps_count=2. Corrige VERIFICATION.md y re-dispara el flujo.',
      ].join('\n'),
    },
    session: { session_id: 's1', task_ref: 'KL-42', phase_id: '10' },
  };
}

function missingResult() {
  return {
    verdict: { action: 'missing', phase_id: '10' },
    plane: {
      commented: true,
      transitioned: false,
      comment_body: [
        '[kodo:gsd] ⚠️ VERIFICATION.md no encontrado para Phase 10',
        '',
        'Ejecuta `/gsd-verify-work` en la sesión y re-dispara el flujo.',
      ].join('\n'),
    },
    session: { session_id: 's1', task_ref: 'KL-42', phase_id: '10' },
  };
}

function malformedResult() {
  return {
    verdict: {
      action: 'malformed',
      phase_id: '10',
      detail: 'missing field must_haves_total',
    },
    plane: {
      commented: true,
      transitioned: false,
      comment_body: [
        '[kodo:gsd] ⚠️ VERIFICATION.md presente pero inválido (Phase 10)',
        '',
        'Detalle: missing field must_haves_total',
        'Corrige el frontmatter y re-dispara el flujo.',
      ].join('\n'),
    },
    session: { session_id: 's1', task_ref: 'KL-42', phase_id: '10' },
  };
}

describe('runGsdVerifyCli — exit codes (Pitfall #6, Opción A)', () => {
  it('C1: verdict pass → exit 0 + render', async () => {
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.equal(code, 0);
    assert.match(stdout.get(), /action:\s+pass/);
    assert.match(stdout.get(), /phase_id:\s+10/);
    assert.match(stdout.get(), /must_haves:\s+8/);
    assert.match(stdout.get(), /commented=true transitioned=true/);
  });

  it('C2: verdict fail → exit 0 (gate corrió, entregó verdict)', async () => {
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => failResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.equal(code, 0);
    assert.match(stdout.get(), /action:\s+fail/);
    assert.match(stdout.get(), /reason:\s+gaps-found/);
    assert.match(stdout.get(), /detail:\s+gaps_count=2/);
    assert.match(stdout.get(), /transitioned=false/);
  });

  it('C3: verdict missing → exit 0', async () => {
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => missingResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.equal(code, 0);
    assert.match(stdout.get(), /action:\s+missing/);
    assert.match(stdout.get(), /phase_id:\s+10/);
  });

  it('C4: verdict malformed → exit 0', async () => {
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => malformedResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.equal(code, 0);
    assert.match(stdout.get(), /action:\s+malformed/);
    assert.match(stdout.get(), /detail:\s+missing field must_haves_total/);
  });

  it('C5: error "session not found" → exit 1', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 'nope' },
      {
        runVerifyFn: async () => {
          throw new Error('session not found: nope');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 1);
    assert.match(stderr.get(), /session not found/);
  });

  it('C6: error "is not GSD" → exit 1', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('session is not GSD: s1');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 1);
    assert.match(stderr.get(), /is not GSD/);
  });

  it('C7: error "provider fetch failed" → exit 2 (transient)', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('provider fetch failed: ECONNREFUSED 127.0.0.1:8000');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 2);
    assert.match(stderr.get(), /provider fetch failed/);
  });

  it('C7b: error ETIMEDOUT también mapea a exit 2', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('request failed: ETIMEDOUT');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 2);
    assert.match(stderr.get(), /ETIMEDOUT/);
  });

  it('C7c: error network también mapea a exit 2', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('network unreachable');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 2);
  });

  it('C7d: error interno genérico → exit 1 (NO transient)', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('state.json not readable');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 1);
    assert.match(stderr.get(), /state\.json/);
  });
});

describe('runGsdVerifyCli — output format', () => {
  it('C8: --json emite JSON parseable con verdict/plane/session', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1', json: true },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    const parsed = JSON.parse(stdout.get());
    assert.equal(parsed.verdict.action, 'pass');
    assert.equal(parsed.verdict.phase_id, '10');
    assert.equal(parsed.plane.commented, true);
    assert.equal(parsed.plane.transitioned, true);
    assert.equal(parsed.session.session_id, 's1');
  });

  it('C9: sin --json NO es JSON parseable (human-readable)', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.throws(() => JSON.parse(stdout.get()));
    assert.match(stdout.get(), /Verdict:/);
  });
});

describe('runGsdVerifyCli — renderHuman switch exhaustive', () => {
  it('C10.pass: incluye action/phase_id/must_haves', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    const out = stdout.get();
    assert.match(out, /action:\s+pass/);
    assert.match(out, /phase_id:\s+10/);
    assert.match(out, /must_haves:\s+8/);
  });

  it('C10.fail: incluye action/phase_id/reason/detail', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => failResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    const out = stdout.get();
    assert.match(out, /action:\s+fail/);
    assert.match(out, /phase_id:\s+10/);
    assert.match(out, /reason:\s+gaps-found/);
    assert.match(out, /detail:\s+gaps_count=2/);
  });

  it('C10.missing: incluye action/phase_id (sin detail)', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => missingResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    const out = stdout.get();
    assert.match(out, /action:\s+missing/);
    assert.match(out, /phase_id:\s+10/);
    // renderHuman missing branch NO debe imprimir "detail:"
    assert.ok(!/detail:/.test(out.split('Verdict:')[1] || ''));
  });

  it('C10.malformed: incluye action/phase_id/detail', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => malformedResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    const out = stdout.get();
    assert.match(out, /action:\s+malformed/);
    assert.match(out, /phase_id:\s+10/);
    assert.match(out, /detail:\s+missing field must_haves_total/);
  });

  it('C11: renderHuman emite línea final "Plane: commented=... transitioned=..."', async () => {
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.match(stdout.get(), /Plane: commented=true transitioned=true/);
  });
});

describe('runGsdVerifyCli — DI determinismo', () => {
  it('C12: runVerifyFn se invoca exactamente una vez con sessionId', async () => {
    let callCount = 0;
    let received;
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 'abc-123' },
      {
        runVerifyFn: async (opts) => {
          callCount += 1;
          received = opts;
          return passResult();
        },
        writeFn: stdout.write,
        errFn: () => {},
      },
    );
    assert.equal(callCount, 1);
    assert.deepEqual(received, { sessionId: 'abc-123' });
  });
});

// =====================================================================
// Plan 15-04 Task 2: verdict→color mapping (D-14) + Plane summary slice
// (D-15) + formatterFn DI + anti-re-render invariant.
// =====================================================================

describe('runGsdVerifyCli — verdict→color mapping (D-14)', () => {
  it('CLR1: verdict pass + TTY → action wrapped in green ANSI', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    assert.equal(code, 0);
    // pass → fmt.green('pass') → \x1b[32mpass\x1b[39m (picocolors)
    assert.match(stdout.get(), /\x1b\[32m.*pass.*\x1b\[/, 'pass debe estar en verde');
    // El cuerpo se imprime sin color
    assert.match(stdout.get(), /phase_id:\s+10/);
    assert.match(stdout.get(), /must_haves:\s+8/);
  });

  it('CLR2: verdict fail + TTY → action wrapped in yellow ANSI', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => failResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    assert.equal(code, 0);
    assert.match(stdout.get(), /\x1b\[33m.*fail.*\x1b\[/, 'fail debe estar en amarillo');
  });

  it('CLR3: verdict missing + TTY → action wrapped in red ANSI', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => missingResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    assert.match(stdout.get(), /\x1b\[31m.*missing.*\x1b\[/, 'missing debe estar en rojo');
  });

  it('CLR4: verdict malformed + TTY → action wrapped in red ANSI', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => malformedResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    assert.match(stdout.get(), /\x1b\[31m.*malformed.*\x1b\[/, 'malformed debe estar en rojo');
  });

  it('CLR5: NO_COLOR / non-TTY → action sin ANSI escapes (literal pass/fail/missing/malformed)', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: false }, {}),
      },
    );
    assert.doesNotMatch(stdout.get(), /\x1b\[/, 'non-TTY no debe emitir ANSI escapes');
    assert.match(stdout.get(), /action:\s+pass/);
    assert.match(stdout.get(), /phase_id:\s+10/);
  });
});

describe('runGsdVerifyCli — Plane comment summary block (D-15)', () => {
  it('SUM1: summary block contiene primeras 3 líneas de comment_body (slice, NO re-render)', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    const fakeResult = {
      verdict: { action: 'pass', phase_id: '10', must_haves: 8 },
      plane: {
        commented: true,
        transitioned: true,
        comment_body: 'LINE1\nLINE2\nLINE3\nLINE4\nLINE5',
      },
      session: { session_id: 's1', task_ref: 'KL-42', phase_id: '10' },
    };
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => fakeResult,
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: false }, {}),
      },
    );
    const out = stdout.get();
    assert.match(out, /Plane comment \(summary\):\n  LINE1\n  LINE2\n  LINE3\n/);
    assert.doesNotMatch(out, /LINE4/, 'slice(0, 3) excluye líneas 4+');
    assert.doesNotMatch(out, /LINE5/);
  });

  it('SUM2: summary block aparece DESPUÉS de Verdict y ANTES de "Plane: commented="', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: false }, {}),
      },
    );
    const out = stdout.get();
    const verdictIdx = out.indexOf('Verdict:');
    const summaryIdx = out.indexOf('Plane comment (summary):');
    const planeStatusIdx = out.indexOf('Plane: commented=');
    assert.ok(verdictIdx >= 0, 'sección Verdict presente');
    assert.ok(summaryIdx > verdictIdx, 'summary aparece después de Verdict');
    assert.ok(planeStatusIdx > summaryIdx, 'Plane: commented= aparece después del summary');
  });

  it('SUM3: summary block presente para los 4 verdicts', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const cases = [
      { name: 'pass', result: passResult() },
      { name: 'fail', result: failResult() },
      { name: 'missing', result: missingResult() },
      { name: 'malformed', result: malformedResult() },
    ];
    for (const c of cases) {
      const stdout = makeStdoutStub();
      await runGsdVerifyCli(
        { sessionId: 's1' },
        {
          runVerifyFn: async () => c.result,
          writeFn: stdout.write,
          errFn: () => {},
          formatterFn: () => createFormatter({ isTTY: false }, {}),
        },
      );
      assert.match(stdout.get(), /Plane comment \(summary\):/, `summary block esperado para ${c.name}`);
      // Header determinista de verify.js debe aparecer en summary slice (slice de comment_body):
      assert.match(stdout.get(), /\[kodo:gsd\]/, `header determinista presente en summary (${c.name})`);
    }
  });
});

describe('runGsdVerifyCli — anti-re-render invariant (Pitfall #2 Phase 10)', () => {
  it('REND1: gsd-verify.js NO importa renderComment ni los sub-renderers', () => {
    const src = readFileSync('src/cli/gsd-verify.js', 'utf-8');
    assert.doesNotMatch(
      src,
      /renderComment|renderPassComment|renderFailComment|renderMissingComment|renderMalformedComment/,
      'el CLI debe consumir result.plane.comment_body (slice), NO re-llamar a los renderers',
    );
  });
});

describe('runGsdVerifyCli — --json mode preserved (Plan 15-04 Task 2)', () => {
  it('JSON1: --json incluye plane.comment_body, NO incluye color ni summary block', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const stdout = makeStdoutStub();
    await runGsdVerifyCli(
      { sessionId: 's1', json: true },
      {
        runVerifyFn: async () => passResult(),
        writeFn: stdout.write,
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    const raw = stdout.get();
    const parsed = JSON.parse(raw);
    assert.equal(typeof parsed.plane.comment_body, 'string');
    assert.match(parsed.plane.comment_body, /\[kodo:gsd\] ✅ Phase 10/);
    assert.doesNotMatch(raw, /Plane comment \(summary\):/, '--json no debe imprimir summary block');
    assert.doesNotMatch(raw, /\x1b\[/, '--json no debe emitir ANSI escapes incluso con TTY');
  });
});

describe('runGsdVerifyCli — exit codes invariantes con color/summary (Plan 15-04 Task 2)', () => {
  it('EXIT1: pass + color + summary block → exit 0 (sin cambios)', async () => {
    const { createFormatter } = await import('../src/cli/format.js');
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => passResult(),
        writeFn: () => {},
        errFn: () => {},
        formatterFn: () => createFormatter({ isTTY: true }, {}),
      },
    );
    assert.equal(code, 0);
  });

  it('EXIT2: error transient (provider fetch failed) sigue dando exit 2', async () => {
    const stderr = makeStdoutStub();
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('provider fetch failed: ECONNREFUSED');
        },
        writeFn: () => {},
        errFn: stderr.write,
      },
    );
    assert.equal(code, 2);
  });

  it('EXIT3: error interno sigue dando exit 1', async () => {
    const code = await runGsdVerifyCli(
      { sessionId: 's1' },
      {
        runVerifyFn: async () => {
          throw new Error('session not found: s1');
        },
        writeFn: () => {},
        errFn: () => {},
      },
    );
    assert.equal(code, 1);
  });
});

describe('src/cli.js — gsd verify subcommand registration (static)', () => {
  const cli = readFileSync('src/cli.js', 'utf-8');

  it('CLI1: registra .command("verify <session-id>")', () => {
    assert.ok(
      cli.includes(".command('verify <session-id>')"),
      "expected literal .command('verify <session-id>')",
    );
  });

  it('CLI2: importa dinámicamente ./cli/gsd-verify.js', () => {
    assert.ok(
      cli.includes("import('./cli/gsd-verify.js')"),
      "expected literal import('./cli/gsd-verify.js')",
    );
  });

  it('CLI3: invoca runGsdVerifyCli', () => {
    assert.ok(cli.includes('runGsdVerifyCli'), 'expected runGsdVerifyCli identifier');
  });

  it('CLI4: descripción documenta idempotencia (Pitfall #7)', () => {
    assert.ok(
      /idempotent|duplicates accepted/i.test(cli),
      'descripción del comando debe mencionar idempotencia',
    );
  });
});
